version: '3'
services:
  nginx-proxy:
    build: ./nginx
    image: 'cmyanko/sonatype_nginx-proxy:2.4'
    ports:
      - '443:443'
      - '5000:5000'
      - '8011:8011'
      - '18443:18443'
    command:
      - nginx
      - '-g'
      - daemon off;
  nexus:
    image: 'cmyanko/nexus3:3.15.2'
    build: ./nexus
    volumes:
      - '~/nexus-data:/nexus-data'
    ports:
      - '8081:8081'
  iq-server:
    image: 'cmyanko/my-iq-server:1.59.0'
    build: ./iq-server
    volumes:
      - '~/iq-data:/sonatype-work'
      - '~/iq-logs:/opt/sonatype/nexus-iq-server/log'
    ports:
      - '8070:8070'
      - '8071:8071'
  jenkins:
    image: jenkinsci/blueocean
    user: root
    volumes:
      - '~/.jenkins:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '8080:8080'
      - '50000:50000'

  listener:
    image: my-webhook-listener:1.0.0
    build: ./listener
    volumes:
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    command:
      - -verbose 
      - -hotreload
      - -hooks=/etc/webhook/test.json
      - -hooks=/etc/webhook/dockerHub-scan.json
      - -hooks=/etc/webhook/nxrm-consume.json
      - -hooks=/etc/webhook/iq-consume.json
    links:
      - iq-server 

  # victoria:
  #   image: 'victoria:1.0.0-44'
  #   build: ./victoria
  #   volumes:
  #     - '~/.victoria/db:/home/nexus/db'
  #     - '~/.victoria/log:/home/nexus/log'
  #     - '~/.victoria/tmp:/home/nexus/tmp'
  #   ports:
  #     - '8090:8090'
  #     - '8091:8091'
  #   depends_on:
  #     - iq-server