apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nexus
  name: nexus
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nexus
    spec:
      containers:
      - image: sonatype/nexus3:3.13.0
        name: nexus
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-claim0
      restartPolicy: Always
      volumes:
      - name: nexus-claim0
        persistentVolumeClaim:
          claimName: nexus-claim0
status: {}
