apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: iq-server
  name: iq-server
spec:
  replicas: 1
  selector:
    io.kompose.service: iq-server
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: iq-server
    spec:
      containers:
      - image: ' '
        name: iq-server
        ports:
        - containerPort: 8070
        - containerPort: 8071
        resources: {}
        volumeMounts:
        - mountPath: /sonatype-work
          name: iq-server-claim0
      restartPolicy: Always
      volumes:
      - name: iq-server-claim0
        persistentVolumeClaim:
          claimName: iq-server-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - iq-server
      from:
        kind: ImageStreamTag
        name: iq-server:1.50.0
    type: ImageChange
status: {}
