apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nexus
  name: nexus
spec:
  replicas: 1
  selector:
    io.kompose.service: nexus
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nexus
    spec:
      containers:
      - image: ' '
        name: nexus
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-claim0
      restartPolicy: Always
      volumes:
      - name: nexus-claim0
        persistentVolumeClaim:
          claimName: nexus-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nexus
      from:
        kind: ImageStreamTag
        name: nexus:3.13.0
    type: ImageChange
status: {}
