apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-proxy
  name: nginx-proxy
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: sonatype_nginx-proxy:2.3
    generation: null
    importPolicy: {}
    name: "2.3"
status:
  dockerImageRepository: ""
